### ISSUE TITLE
shared information between two human worker in one conversation.

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/Mephisto#236]
I'm developing a human-human chat collection task, which needs to present a shared message between two workers before the conversation. There are two problems I don't know how to solve:
1. In one chat task, two human workers need to share the same message before the conversation. 
2. Shared messages are different across tasks.

I plan to present this message in _MTurkOnboardWorld_ class. But, it looks like this class needs _assignment_id_ to solve the above problems. I don't know where I can get _assignment_id_  and pass it to _MTurkOnboardWorld_ class.

Is there any way to solve these problems?

**Comment by JackUrb** [comment]
You don't necessarily need to use an `MTurkOnboardingWorld`, or onboarding at all. All you really need for this is to ensure that on the first `parley` call, you send messages to the agents in the world. 

For 1) something like the below should suffice:
```python
...World():
  def  __init__(self, ...):
    ...
    self.sent_first_message = False

  def parley(self):
    if not self.sent_first_message:
      self.agents[0].observe(...)
      self.agents[1].observe(...)
      self.sent_first_message = True
    # proceed normally
```

If the goal for 2) is to work though a stack of first messages, you can initialize that stack in your run file, and pass that stack as part of `world_opt`. You can then pass it through to your world in `make_world` and retrieve a message during `__init__`. Lastly ensure in `world.shutdown()` that you return the message to the stack if it the world didn't complete (like if one worker disconnected).

**Comment by WilliamsToTo** [comment]
Thanks. That's very helpful.

**Comment by neptune233** [comment]
Hello, previously I used similar code to run locally. The information is correctly displayed to the two agents. However, when I deploy it to the sandbox, the second user who enters the task will see the same information displayed twice. What will be the reason cause that? Thanks for you help.
![Screenshot from 2020-11-07 17-09-51](https://user-images.githubusercontent.com/46469291/98437308-1b8da280-211c-11eb-8afd-29eec7a2e0e5.png)

**Comment by JackUrb** [comment]
This appears to be a regression - I'll address this on Monday, thanks for flagging!

**Comment by neptune233** [comment]
Hi, thank you for updating the code. The double message is solved in common setting of task. Athough this problem is still existing when use onboarding. After the onboarding finish, when the second worker finishes onboarding, the message still will be presented twice.

**Comment by JackUrb** [comment]
The issue is resolved in #311, though we haven't yet pushed a new version of  `mephisto-task` containing it.

**Comment by neptune233** [comment]
Thanks for your reply. I am a bit confused because I was testing based on the modified code in #311.   Do you mean that packages/mephisto-task/src/socket_handler.jsx in the last commit is not the final version? Because the double message still happens when using onboarding setup using the changed code.

**Comment by JackUrb** [comment]
Unfortunately unless you're manually linking to the local package (which if you are then I need to try and repo) you won't see the changes in the output bundle even if you've checked the code out locally.

**Comment by neptune233** [comment]
I use the following code to do the linking
`cd packages/mephisto-task`
`npm link`
`cd <app folder>`
`npm link mephisto-task`
But the double messages still happens. Because I am new to react, is what I did correct? 
If it's wrong, what is the correct approach to do a linking? Thanks for you help.

**Comment by JackUrb** [comment]
I've had some issues with linking the NPM packages in my own builds as well - @pringshia do you have more guidance on how this should work? We could also just push these changes live.

**Comment by pringshia** [comment]
Hi @neptune233 - I have published a new version of the `mephisto-task` package (v1.0.13) which includes the fix Jack mentioned from #311. If that works - great - otherwise I can help walk through your set up to see why you may be experiencing the issues with `npm link`.
